### ISSUE TITLE
Cortical gray matter appears to be too thin.  

### ISSUE THREAD

**Issue by sj-choi** [ANTsX/ANTsPyNet#105]
I ran deep_atropos and cortical_thickness on some data, but noticed that the cortical gray matter (GM) seems abnormally thin.

T1w
![t1](https://github.com/ANTsX/ANTsPyNet/assets/1088166/be65a515-04c1-4531-b561-fc31108889ef)

deep atropos 
![deep_atropos_test](https://github.com/ANTsX/ANTsPyNet/assets/1088166/c2a86c6a-714f-42a6-86ae-476cd95d787a)

It would be helpful to know if there are control parameters available for the deep_atropos, deep_flash, DKT, and cortical_thickness utilities.  

It would be helpful to receive guidance on understanding thickness_image following cortical_thickness.
![cortical_thickness_test](https://github.com/ANTsX/ANTsPyNet/assets/1088166/b5f0f69c-9165-4494-89a5-92c4a0e67912)

**Comment by ntustison** [comment]
There are essentially no tunable parameters for the functions in antsxnet.  Any change in output would require preprocessing on your data prior to input into the antsxnet programs.  For example, in this particular image, the gm/wm contrast is not good which is probably causing the overly thin cortex in deep_atropos.  Perhaps if you can improve that, you'd get better results.  Otherwise, you might want to look at some of our pre-antsxnet tools in ANTsX if you need something tunable.

**Comment by sj-choi** [comment]
Thank you for your reply. I understand that to utilize ANTsXNet tools, enhancing the input image quality might be necessary. However, since ANTsXNet tools already include default preprocessing, I might be inputting an already preprocessed image into these tools, which will then undergo further internal preprocessing. Is my understanding correct?

**Comment by ntustison** [comment]
Yes.

**Comment by cookpa** [comment]
@sj-choi can you share the ANTsPyNet version and the commands you ran?

Regarding the thickness image, it is a floating point image, you should load it as a grayscale overlay in ITK-SNAP, not as a segmentation (which must be positive integer labels).

**Comment by sj-choi** [comment]
> @sj-choi can you share the ANTsPyNet version and the commands you ran?
> 
> Regarding the thickness image, it is a floating point image, you should load it as a grayscale overlay in ITK-SNAP, not as a segmentation (which must be positive integer labels).

cr_thk = os.path.join(file_location, "ANTsPyNet_labels", f"{scancode}-CR_THK.nii.gz")
if not os.path.exists(cr_thk):
    cth_results = antspynet.cortical_thickness(t1, verbose=True)
    ants.image_write(cth_results['thickness_image'], cr_thk)
else:
    print(f"{cr_thk} already exits.")

**Comment by sj-choi** [comment]
> Just to add a bit more---the "preprocessing" performed by the various functions are limited to standard steps such as bias correction and denoising. The problem you're seeing with your data pops up occasionally and is certainly problematic but not systematic so it's hard to fix unless we accumulated all these problematic cases and, once we have enough, retrain the network. But that's not likely to happen soon given the rarity of occurrence. One specific preprocessing step you can try is histogram matching or histogram equalization (both in ANTsPyNet or ANTsPy) to change the gm/wm contrast. That has worked for me in the past but there's no guarantee that it'll work here.

Thank you very much for your suggestion. I will try those tools and retry the ANTsXNet tools.

**Comment by sj-choi** [comment]
@ntustison What would you recommend as a reference image for the histogram matching or histogram equalizing?

**Comment by ntustison** [comment]
If I'm doing a study, I would run all my data through the pipeline and then look at the results.  For a problematic case like this, I would use one of the ones that "worked" for histogram matching (histogram equalization doesn't require a source image) or perhaps a cohort-specific template.

**Comment by sj-choi** [comment]
I appreciate your recommendation. I've noticed that ANTs provide tools for building a cohort-specific template. I plan to explore this further.

**Comment by sj-choi** [comment]
@cookpa Could you guide me to use the cortical thickness properly?

**Comment by ntustison** [comment]
Just FYI, denoising is done as part of the preprocessing in ``deep_atropos``.

**Comment by sj-choi** [comment]
I tried histogram matching with Kirby S_tamplate3.nii.gz as a reference image. The result improved as shown below. (The identical case and the same slice shown above.)
  
![hm_deep_atropos](https://github.com/ANTsX/ANTsPyNet/assets/1088166/7a3401ad-e048-4138-b02b-c3002d4911f1)

**Comment by stnava** [comment]
hmm - this is a very interesting result.    

worth further investigation as to the meaning of it.   

immediate thoughts regard implications for multi-site data reproducibility etc ( can easily test ) 

I have SRPBS and other traveling cohort data on hand so if someone could specify an experiment, I could run it.

**Comment by sj-choi** [comment]
When I used the MNI152 template for histogram matching, the result was worse than the original.

**Comment by ntustison** [comment]
Just an FYI, @stnava but ``deep_atropos`` was not trained with histogram warping augmentation.  Since ``deep_atropos`` was one of the earliest networks we trained, and we've learned a lot, specifically with respect to data augmentation, I've often thought that an updated trained network might be worthwhile.  Although it's such a core network that I'm obviously hesitant to change anything.

**Comment by stnava** [comment]
assuming `antspynet.cortical_thickness` does deep learning based processing then it would seem important and useful to provide a method that ensured the input histogram fit within the training distribution.    this is a seemingly trivial step but assuredly very important.   likely we could improve  results if this were investigated further.

**Comment by stnava** [comment]
@ntustison - got ya ... I think worth doing.  i have reference data and can do a large reprocess to compare against if you pull the trigger on it.   but the other issue is the resolution.  would prefer a high-res network.   solution being => run SR on training data.  then retrain.    I can spin up an AWS A100 cluster if that would help.

**Comment by ntustison** [comment]
Great.  I think this could potentially benefit from what you, @cookpa, and I recently discussed re. templates.  Specifically, another potential issue about ``deep_atropos`` that we might want to reconsider is training in MNI space and, as you said, the use of SR.  I mentioned to Phil that I should have some results next week that I was planning to share with both of you.  I'll put this on my to-do list and will certainly think about but won't actually start training until after we've had some decisions with respect to this current work.

**Comment by stnava** [comment]
ok - for reference - https://github.com/stnava/siq

**Comment by ntustison** [comment]
Thanks.   Yeah, I'm sure I'll have to consult with you when I get to the SR part.

**Comment by stnava** [comment]
ok - re: training data ...  had mentioned I prefer HCP but one aspect of UKBB that is nice is the fairly strict curation ... perhaps an unbiased strategy would be to use both

**Comment by sj-choi** [comment]
@cookpaI appreciate your tip for using cortical thickness results. I assume the numbers are in units of mm.

**Comment by cookpa** [comment]
Yes, `mm`.

**Comment by sj-choi** [comment]
@cookpa  Thanks for your confirmation.
