### ISSUE TITLE
Testing other models for brain age predicition

### ISSUE THREAD

**Issue by abanic7** [ANTsX/ANTsPyNet#108]
Hello,

Is there a way i could download model in .h5 format that is not on the valid list in: "get_pretrained_network" and use it instead of deepbrainnet that is the deafult option?

**Comment by ntustison** [comment]
To which network are you referring?

**Comment by abanic7** [comment]
I found some models here that i would like to try out:
https://upenn.app.box.com/v/DeepBrainNet/folder/120404890511

**Comment by ntustison** [comment]
No, you'd have to reproduce those networks yourself to be able to load those other weights.

**Comment by abanic7** [comment]
What do you mean? In your function, get_pretrained_network you just download the h5 file of the deepbrainnet? Why can't i download some other model myself?

**Comment by ntustison** [comment]
Okay, I now understand what you're saying.  YOu can't access the other models through the ANTsPyNet interface.  I was only interested in one of them when I wrote the function.  However, it should be straightforward to use the same code to use the other models.

**Comment by abanic7** [comment]
Is there a way i can use my gpu instead of cpu when using brain_age function?

**Comment by ntustison** [comment]
That's a system-specific keras issue, not an antspynet issue.  You should be able to find what you're looking for with a web search.
