### ISSUE TITLE
Requirements for pypi releases

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTsPyNet#110]
Fantastic! This will help me a ton. Need help getting a pypi release up? Here is the [GHA workflow](https://github.com/nitrain/nitrain/blob/main/.github/workflows/python-publish.yml) I use personally to automatically push to pypi every time you make a new release on github. Just requires setting the pypi token as a repo secret.

_Originally posted by @ncullen93 in https://github.com/ANTsX/ANTsPyNet/issues/93#issuecomment-2080379979_

**Comment by cookpa** [comment]
@ncullen93 thanks for this - starting a new issue for it

**Comment by cookpa** [comment]
One thing I wanted to ask (re: #108) is whether the requirements should be tensorflow-gpu instead of tensorflow.

I'm less familiar with keras, is there an equivalent like keras-gpu? Or does normal keras just work?

**Comment by cookpa** [comment]
Huh, looks like `tensorflow-gpu` is now [deprecated](https://pypi.org/project/tensorflow-gpu/). So hopefully we're good on that front. I guess it's down to individual users to make sure they install a tensorflow that is compatible with their cuda version according to 

https://www.tensorflow.org/install/source#gpu

**Comment by ntustison** [comment]
Good to know.  Thanks.
