### ISSUE TITLE
Can't install today

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTsPyNet#115]
```pip install git+https://github.com/ANTsX/ANTsPyNet.git ```

appears to work but then

```
$ python
Python 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import antspynet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/miniconda3/envs/antspynet_today/lib/python3.10/site-packages/antspynet/__init__.py", line 5, in <module>
    from .architectures import *
ModuleNotFoundError: No module named 'antspynet.architectures'
>>> 
```

**Comment by cookpa** [comment]
`pip install git+https://github.com/ANTsX/ANTsPyNet.git@2a2384510ab6856e0774965b47772e339c89cb3d`

works fine

**Comment by ntustison** [comment]
Yeah, I just updated about 20 minutes ago and am getting a ModuleNotFoundError although it's referring to a specific function.  I'm trying to figure it out now.

**Comment by stnava** [comment]
thx - just started seeing this .... I erroneously pushed a pypi release with this bug .... let us know when fixed.

**Comment by ntustison** [comment]
@cookpa , are you seeing that this only happened with @stnava 's recent pushes?  I don't think it was anything I did.

**Comment by cookpa** [comment]
I think it's to do with the changes to `pyproject.toml` by @stnava. Brian, I see you went back to a hard-coded version string, which I think is necessary because I could not get ANTsPy to work with an automatically generated version. 

<img width="1212" alt="image" src="https://github.com/ANTsX/ANTsPyNet/assets/611507/b73b6346-76a1-45e2-afbd-9a320f5ad203">

But something is breaking the import

**Comment by cookpa** [comment]
I also think we needed the `keras<3` because users were reporting errors

**Comment by ntustison** [comment]
@stnava @cookpa Can we just revert back, at least for now?

**Comment by stnava** [comment]
I think it's currently fixed.   issue was numpy requirement.

**Comment by ntustison** [comment]
Great.  Thanks.  I'll check it out on my end.

**Comment by stnava** [comment]
seems "fixed" for source install at least ... the wheel may still be broken .... not sure why yet

**Comment by stnava** [comment]
yes - wheel is still not right .... this seems to have something to do with  a more "modern" way of setting up packages via import lib

**Comment by cookpa** [comment]
It's something to do with paths. It seems to work if I am in the source directory. Previously it would not work from there because of circular imports

**Comment by stnava** [comment]
ok ... I dont have issues on 3.12 but do on 3.9

**Comment by stnava** [comment]
scratch that - dont have issues on OSX 3.12 .... but do on linux 3.9 and possibly linux 3.12

**Comment by cookpa** [comment]
Does the source install work for you if you are not in the source directory?

**Comment by stnava** [comment]
source install works in every case

**Comment by cookpa** [comment]
It's not working for me on Mac or Linux.

```
git clone git@github.com:ANTsX/ANTsPyNet.git
pip install ./ANTsPyNet
```

Whereas this works

```
git clone git@github.com:ANTsX/ANTsPyNet.git
cd ANTsPyNet
pip install .
python
>>> import antspynet
```

As does the mistaken

```
git clone git@github.com:ANTsX/ANTsPyNet.git
# Below actually installs from pypi!
pip install ANTsPyNet
```

**Comment by stnava** [comment]
should be fixed

**Comment by stnava** [comment]
key missing piece the __antspynet.*__:

```
find = { include = ["antspynet","antspynet.*"] }
```

**Comment by stnava** [comment]
yeah - this was all so I could get a  more up to date antspynet pypi release and enable some testing via circleci
