### ISSUE TITLE
Issue with initialization of DDSRCNN model

### ISSUE THREAD

**Issue by xdavidg** [ANTsX/ANTsPyNet#119]
Hello,

When I try to initialize the deep denoise super resolution model with the given sample input:

model = create_deep_denoise_super_resolution_model_3d((128, 128, 128, 1))
model.summary()

I run into the following error:

ValueError: Inputs have incompatible shapes. Received shapes (128, 128, 128, 64) and (256, 256, 256, 64)

I've tried with additional shapes and also have the same error. I've made no modifications to the original code for creating the architecture. Am I doing something wrong, or is it expected to modify the code for it to run?

**Comment by ntustison** [comment]
Thanks.  I need to remove this architecture as it's not used and has been broken for awhile. I haven't looked into fixing it as we don't use it for anything.

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTsPyNet/commit/47724bf0c8a3be5e3501f1fc14d32cb14a961229

**Comment by xdavidg** [comment]
In that case, which architectures would you recommend to train for super resolution of brain MRIs? I'm working on a project where I am tasked with super resolving MRIs of a non-human species and therefore need to pre-train it myself.

**Comment by ntustison** [comment]
[Here's a self-contained example](https://gist.github.com/ntustison/12a656a5fc2f6f9c4494c88dc09c5621#mri-super-resolution) of our MRI super-resolution network.   It has fairly generic applicability and good performance so I would suggest trying it first before training your own.  It's based on this [deep back projection network](https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/architectures/create_deep_back_projection_network_model.py) with a performance evaluation described [here](https://www.medrxiv.org/content/10.1101/2023.02.02.23285376v1).

**Comment by xdavidg** [comment]
Hey @ntustison, I just wanted to thank you for your help. The model you suggested is a great baseline for me to work with and has already very impressive results for my data. I really am grateful that a resource like this exists for someone like me who's just dipping their toes into the topics of deep learning for medical image computing.

**Comment by ntustison** [comment]
Great.  Glad it worked for you.  I'm sure you noticed it's memory requirements are fairly significant so you might have to do a patch-wise approach.  Regarding training, note that almost every set of network training scripts are informally organized located [here](https://github.com/ntustison/ANTsXNetTraining).  A notable exception is super-resolution as I didn't do the training.  However, they can give you an idea of some of the data augmentation steps that we have available.

**Comment by stnava** [comment]
SR training methods are here https://pypi.org/project/siq/

**Comment by stnava** [comment]
no problem .... just note that SR is not specific to a modality or even a species.  it cares more about primitive image features in the sense of what's defined by people like Eero Simoncelli.
