### ISSUE TITLE
pretrained weights

### ISSUE THREAD

**Issue by WAMAWAMA** [ANTsX/ANTsPyNet#12]
It's a great job， but is there a simple, quick and easy way to get pre-trained weights？Can pre-trained weight download and loading be done automatically by the script？

**Comment by ntustison** [comment]
Yes, all weights and image data are downloaded automatically within the scripts.  For example, try this

```
>>> import ants
>>> import antspynet
>>> t1 = ants.image_read(antspynet.get_antsxnet_data("S_template3"))
>>> brain_extraction = antspynet.brain_extraction(t1, modality="t1", verbose=True)
```

**Comment by WAMAWAMA** [comment]
tks a lot ， i just find the code for downloading and loading pretrained weights at [get_pretrained_network.py](https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/get_pretrained_network.py), this is really convenient for doing research, and hope for giving more Tutorials and examples(such as colab notebook) in future👍
