### ISSUE TITLE
Issue regarding to apply brain parcellation to MRI images for specific brain regions at P56 mice

### ISSUE THREAD

**Issue by TsungChihTsai** [ANTsX/ANTsPyNet#121]
Original title is "Issue regarding to apply "DevCCF Velocity Flow Model" to other MRI data". It's out of focus. Therefore, I revised the title above (19 Jun, 2024):

</head>

<body link="#0563C1" vlink="#954F72">

Issue regarding to   apply "DevCCF Velocity Flow Model" to other MRI data
--

</body>

</html>

Thanks for your remarkable work. I'm not proficient in coding, I require your help. Before I raise the issue I'm facing, I'd like to explain my current situation.

I have referenced your work in "The ANTsX Ecosystem for Mapping the Mouse Brain (2024)". I've attempted to revise to execute the tutorial codes of python from https://gist.github.com/ntustison/12a656a5fc2f6f9c4494c88dc09c5621#mouse-applicatons. And, I also attempted to use the pipeline of "Table 1: Sampling of ANTsX functionality," there are still some challenges to overcome for me. 

<img src="https://github.com/ANTsX/ANTsPyNet/assets/123632629/aee3d594-5649-4525-bd2a-48b114d015b1" width="450" height="500" alt="download">

By **using the mouse_brain_extraction by antspynet** to process **an open source MRI data** (https://figshare.com/ndownloader/files/45289309). I can get a whole mouse brain. 
<img src="https://github.com/ANTsX/ANTsPyNet/assets/123632629/251cb166-20d1-49fd-980f-67a62b98ea11" width="200" height="200" alt="mouse_brain_extracted_animation">

By **using the ants.n4_bias_field_correction, ants.denoise_image , ants.registration, and antspynet.mouse_brain_parcellation**, I can get major brain regions, such as the olfactory bulb, cortical area, midbrain, hippocampus, and cerebellum. 
<img src="https://github.com/ANTsX/ANTsPyNet/assets/123632629/56ef73e2-49ce-4564-8e01-448715b7373e" width="200" height="200" alt="mouse_brain_parcellation_segmentation_animation">

**My purpose is that** effectively get some specific adult mouse brain area, such as the medial prefrontal cortex (mPFC),  medial dorsal (MD) thalamus. Thus, I came across your work on the "Developmental Mouse Brain Common Coordinate Framework (2023)", where you introduced the developmental common coordinate framework (DevCCF). This model can show clear brain area in different developmental stages (https://kimlab.io/brain-map/DevCCF/) . 

1. After I attempted to use your code (https://github.com/ntustison/ANTsXMouseBrainMapping), I followed your procedure and built the DevCCF Velocity Flow Model (DevCCF_velocity_flow.nii.gz).  However, when I ran the code for "Using the DevCCF Velocity Flow Model", **the template_file did not define before this cell**. 
![thumbnail_image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/8105ea0f-6e29-48c3-8a93-0ef93c3950d0)

2. I am also unsure **how could I apply this model to other MRI images data.** Could you please guide me how to utilize your code (python) from the directories ANTsXMouseBrainMapping-main\Scripts\BrainExtractionNetwork, MiscScripts, and MultiTissueNetwork? 
![thumbnail_image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/339ffa01-720d-4381-a801-9a41a3fb7f24)

Thank you. If you need more information, please let me know.

**Comment by ntustison** [comment]
Okay, I think you're conflating a couple things so let's try to sort them out first.  The paper describes a couple different methods for completely separate tasks.  The DevCCF velocity flow model has nothing to do with the mouse brain parcellation work.  

From what you wrote, I'm guessing that you want to take as input a mouse brain MRI and parcellate it into a set of regions.  Is that correct?  If so, I have two questions:

* What is the MRI modality that you're using?
* What are your desired brain parcellation regions?

**Comment by TsungChihTsai** [comment]
Thanks for your clarification. I am afraid that I misunderstood your response. So I just confirm my understanding. The DevCCF velocity flow model serves as a comprehensive atlas for all developmental stages of the brain. By applying this model, we will be able to obtain the corresponding structures at each developmental stage. Initially, I also wanted to conduct longitudinal studies to observe changes in desired brain regions’ sizes at different developmental stages.  Is it impossible to do so? However, brain parcellation is a different module to segment the brain area with different training dataset. Therefore, the DevCCF velocity flow model resolve the issue of having a mouse brain atlas for each developmental stage that we have never seen before?

Regarding the questions: 

1. Because now I am just evaluating whether it is possible to do segmentation from a T2 MRI image. I propose to use T2 MRI image. 

2. My desired brain parcellation regions are the medial prefrontal cortex (mPFC), medial dorsal (MD) thalamus, ventral hippocampus (vHP), and cerebellum.

**Comment by ntustison** [comment]
Thanks for your answers.  Follow-up---

* For your longitudinal studies, what ages are you imaging?

**Comment by TsungChihTsai** [comment]
I think anesthesia control is also difficult for pups and in obtaining longitudinal fMRI images. If possible, I’d like to scan P10, P28 and P56. However, for the first step, I‘d like to check the difference at P56. Because I realize this is hard to get precise volume for my desired brain parcellation regions.

**Comment by ntustison** [comment]
Unfortunately, your responses are confusing such that I don't know what you're trying to accomplish using the tools I discuss in the manuscript.  For example, I don't know what fMRI has to do with anything we've discussed nor do I understand what you mean by "the difference at P56." 

Please lay out in very clear terms the design of your study.  Otherwise, I'm going to suggest you try to read the paper again and look at the self-contained tutorials I've created to figure it out yourself.

**Comment by TsungChihTsai** [comment]
fMRI was a typo; I meant MRI. By “the difference at P56,” I am referring to different genotypes. I believe we should start by focusing on the brain parcellation regions at P56, which include the medial prefrontal cortex (mPFC), medial dorsal (MD) thalamus, ventral hippocampus (vHP), and cerebellum. However, I haven’t found a suitable method to accomplish this.

**Comment by ntustison** [comment]
Thanks.  But this illustrates why our conversation has been so confusing.  From the start I had assumed "focusing on the brain parcellation regions at P56" but then you brought in the DevCCF model and a potential longitudinal component which is not relevant to this specific task.  

So, focusing on P56, let's start simple---are you able to run this [example](https://gist.github.com/ntustison/12a656a5fc2f6f9c4494c88dc09c5621#mouse-brain-parcellation)?

**Comment by TsungChihTsai** [comment]
Sorry about that. I lost my focus.
Thank you for helping me get back on track. 

I ran it, 
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/6fc7e271-4418-4955-83d4-dba47bbd1686)

And, I also checked segmentation and probability images, I think it can separate olfactory bulb, cortical area, midbrain, hippocampus, and cerebellum.
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/ee58936a-283e-48ac-871e-902ebff0aa16)
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/8c85d8fc-d7bb-4214-a4e1-335ed760b9fd)
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/95456ac1-f20e-4e2c-9dcb-8e7a7b3dd676)
....
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/e85acf12-ad7a-484c-8236-6e5ff91a28a1)

the probability images have 7 sets.  


However, I found it still have challenge to dissect "medial prefrontal cortex (mPFC), medial dorsal (MD) thalamus, ventral hippocampus (vHP), and cerebellum". Because I also saw this masterpiece: https://kimlab.io/brain-map/neuroglancer/DevCCF/index_P56.html, I think it has the potential to resolve this issue. 

![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/cb056ada-d241-4888-bd27-112402f55062)
Like this part, it can show the area of medial dorsal (MD). That's why I'm seeking this model and lost the focus.

**Comment by ntustison** [comment]
Okay, perfect.  Let's stay simple for now and not bring up Yongsoo's work as I don't think it's relevant, at least not yet.

So what I propose in the manuscript is a specific brain parcellation scheme.  This is one that I generated simply as an example to use with T2-w.  That's why I refer to it in the option as ``which_parcellation = "nick"``.  However, one can easily adapt the same framework for creating other parcellations.  For example, after I wrote the paper, Yongsoo wanted to create a parcellation for serial two-photon tomography images consisting (STPT) of four regions.  You can access that functionality using ``which_parcellation="jay"``.  But note that it *only* works with STPT images.   

It sounds like you want to do something analogous with your regions:  medial prefrontal cortex (mPFC), medial dorsal (MD) thalamus, ventral hippocampus (vHP), and cerebellum.   Since you're analyzing P56 images, I believe you can use the Allen brain atlas to get these regions.  Are you familiar with the allensdk python library?

**Comment by TsungChihTsai** [comment]
Thanks for you suggestion! I am not familiar with allensdk python library. However, I can read this "https://allensdk.readthedocs.io/en/latest/reference_space.html" first.  Could I use this "https://github.com/ntustison/ANTsXMouseBrainMapping/blob/main/Scripts/MiscScripts/get_allen_parcellation.py"?

**Comment by ntustison** [comment]
Yes.  See if you can run that script to get the original "nick" parcellation.  Note that you'll have to download my reoriented version of the Allen template at 50 um resolution available [here](https://drive.google.com/file/d/1xEvbdPHHlJEnUb2K0yMdGgspYVOdA2Fy/view?usp=sharing) and replace the [file path](https://github.com/ntustison/ANTsXMouseBrainMapping/blob/main/Scripts/MiscScripts/get_allen_parcellation.py#L29) in the script.  This reoriented file is necessary to bring Allen into canonical orientation (analogous to human brain imaging).  Let me know when you're able to run the script successfully.

**Comment by TsungChihTsai** [comment]
I will. Thanks for your patience and guidance. Keep in touch.

**Comment by TsungChihTsai** [comment]
Thanks for your note. 

I revised the "get_allen_parcellation.py" script to align with my desired brain parcellation regions:
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/836b5e0d-93ad-4f4a-ac05-7a71ce2b97f1)

And, I ran "get_allen_parcellation.py"

It generates "combined_mask.nii.gz". The image shows as below: 
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/fa54d896-bd1b-4e8f-a48e-b0d4ea76634f)

I get the mask it's what I need. 




![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/59825ddd-b468-40ff-9c36-7c0fa9ee2350)
So, will I create a new "which_parcellation" by this "combined_mask.nii.gz" to operate "antspynet.mouse_brain_parcellation"? 
Or, could I define the "mask" as this "combined_mask.nii.gz" for my next step?

**Comment by ntustison** [comment]
Great.  Can you email it to me or post it somewhere so I can make sure you're ready for the next step?

**Comment by TsungChihTsai** [comment]
Sure! 

Like this way?
[combined_mask.nii.gz](https://github.com/user-attachments/files/15907068/combined_mask.nii.gz)

**Comment by ntustison** [comment]
Okay, so this is a great start.  However, I would add some additional labels that complement your existing labels so that your entire brain is filled.  So, for example, I would add the olfactory bulb, maybe the rest of the cerebral nuclei, cortex.  And then whatever other label such that the entire brain region is filled.  Does that make sense?

**Comment by TsungChihTsai** [comment]
Yes. It might be if I don't fill the whole brain, it cannot perform well for mouse_brain_parcellation. 

![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/11bb16e7-3264-4b07-ad20-7b7c3bca536a)
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/8a139bc6-4775-4c9f-9d9c-21b5dba6e85f)

Original one look like this: 
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/f9b81c14-8bef-4fb2-ae16-6f1fb329acd2)

Revised one look like this: 
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/b59655c4-a929-4d4d-ab4a-b5bcea8bd6c4)

Is it okay? 
[combined_mask.nii.gz](https://github.com/user-attachments/files/15907298/combined_mask.nii.gz)

**Comment by ntustison** [comment]
Yeah, I would go with something like this.  This assessment is based on multiple years of experience.  

Do you have a GPU for training?

**Comment by TsungChihTsai** [comment]
I appreciate your guidance. It makes things straightforward.

I have a desktop in the lab with an NVIDIA Quadro RTX A2000 12GB. Is it available?

I can try it. But, I have a concern. Because when I attempted to do some spike sorting works in Matlab GUI, this desktop worked slowly. I'm not sure if this desktop is affordable for your training task.

**Comment by ntustison** [comment]
Yeah, that's kind of small.  I'll throw it on my GPU tomorrow and we can take a look at the results in a couple days.  I'll let you know.

**Comment by ntustison** [comment]
I was looking at the current results and comparing it with what you have above.  It appears that you have 9 non-background regions but your combined mask only has 7:

```python
>>> mask = ants.image_read("/Users/ntustison/Downloads/combined_mask.nii.gz") 
>>> geoms = ants.label_geometry_measures(mask)
>>> geoms['Label']
0     5
1     6
2     7
3     8
4    10
5    11
6    15
Name: Label, dtype: int64
```

I should've mentioned that your brain regions shouldn't overlap.  I don't know if that is the case here but look at your combined mask and see if it has all the regions you want.  If it's okay, then training should be pretty close to finished.  Otherwise, you'll have fix your combined mask.

**Comment by TsungChihTsai** [comment]
I am sorry. I made a mistake I selected brain regions overlap, so I revised the selection of masks. 

The first six masks are my interesting area, and added 26 other mask area to fill the background. 
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/36ed4c21-cefe-4a66-9738-da52be9b56b6)

The new combined_mask is attach below: 
[combined_mask.nii.gz](https://github.com/user-attachments/files/15930431/combined_mask.nii.gz)

I ran your code for checking the number of masks. Like this five I selected, the others are background for me (total is 32 masks). 
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/73f06d59-8952-466f-8d2f-f79598cf036e)

Could we have a method to combine the masks from label 7 to label 32?

**Comment by ntustison** [comment]
Your proposed labeling is excessive for the image features that are typically visible in standard T2-w images.

**Comment by ntustison** [comment]
Nm, I see what you're saying.  Yes, I can combine labels 7-32 to form a single label.  Let me see how that looks.

**Comment by ntustison** [comment]
Here's the result.  

[combined_mask_tct.nii.gz](https://github.com/user-attachments/files/15930626/combined_mask_tct.nii.gz)

**Comment by ntustison** [comment]
Actually, I'd probably go with this:

[combined_mask_tct2.nii.gz](https://github.com/user-attachments/files/15930647/combined_mask_tct2.nii.gz)

**Comment by TsungChihTsai** [comment]
Thanks! 
So, you combine labels 7-32 to form a single label (index number 0) in combined_mask_tct2.nii.gz. 

![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/aa72d30d-555f-4bc3-8335-19ad8bd32ebe)

**Comment by ntustison** [comment]
Yes.  Did you view it to make sure it's what you expected?

**Comment by TsungChihTsai** [comment]
Yes, they are in the right place.

**Comment by ntustison** [comment]
Okay, I restarted training with these updated labels.  It'll probably take 2-3 days.  I'll let you know when it's finished.

**Comment by ntustison** [comment]
Okay, I added the parcellation "tct" to the repo.  I also added it as part of the [example]( https://gist.github.com/ntustison/12a656a5fc2f6f9c4494c88dc09c5621#mouse-brain-parcellation).  To avoid having to do the work myself, please tell me what the labels are so I can add them [here](https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/mouse.py#L334-L341).

**Comment by ntustison** [comment]
And [here](https://github.com/ntustison/ANTsXNetTraining/tree/main/Mouse/BrainParcellation/TctParcellation) are the training scripts.

**Comment by TsungChihTsai** [comment]
We have 7 labels, but the label number 0 is background. Thus, I need to confirm this with you. 

If we contain the background, the label lists look like as below:  
* "tct" - t2w with labels:
- 1:  background 
- 2: Prelimbic area
- 3: Infralimbic area
- 4: Medial group of the dorsal thalamus
- 5: Reticular nucleus of the thalamus
- 6: Hippocampal formation
- 7: Cerebellum

If we exclude the background, the label lists look like as below:  
* "tct" - t2w with labels:
- 1: Prelimbic area
- 2: Infralimbic area
- 3: Medial group of the dorsal thalamus
- 4: Reticular nucleus of the thalamus
- 5: Hippocampal formation
- 6: Cerebellum

**Comment by ntustison** [comment]
Awesome.  Thanks.  I added that to the documentation.

**Comment by TsungChihTsai** [comment]
Thanks a million! I saw you added those information. 


I attempted to use this https://gist.github.com/ntustison/12a656a5fc2f6f9c4494c88dc09c5621#mouse-brain-parcellation

First, I reinstall antspynet: 
pip uninstall antspynet
python -m pip install antspynet

,then ran
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/6ae6f66e-8d16-4699-b073-df57e6d2d0ff)
It's fail. 

Oh! It's a new version. Then, I think I can copy 
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/0ec731ed-ce97-40f5-adab-1812225d9d02)
and paste into folder: "Lib\site-packages\antspynet\utilities". 


And, then re-open jupyter notebook and ran again. It works!
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/74bba997-9b44-4bf2-aa17-55ada5e2c70f)

However, I found an issue is that it generates 8 masks. I guess the training mask is from 8 labels of [combined_mask_tct.nii.gz](https://github.com/user-attachments/files/15930626/combined_mask_tct.nii.gz), not 7 labels of [combined_mask_tct2.nii.gz](https://github.com/user-attachments/files/15930647/combined_mask_tct2.nii.gz)

I also found another issue is I cannot generate the all the 'probability_images' . It only show five pictures. 
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/47af2f0d-8879-452a-8f0a-7d6b5774243c)
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/a8a1a53b-8b0c-499f-9314-e86a50454397)

**Comment by ntustison** [comment]
Everything is correct.  You just need to do a bit more investigation.

> However, I found an issue is that it generates 8 masks. I guess the training mask is from 8 labels of [combined_mask_tct.nii.gz](https://github.com/user-attachments/files/15930626/combined_mask_tct.nii.gz), not 7 labels of [combined_mask_tct2.nii.gz](https://github.com/user-attachments/files/15930647/combined_mask_tct2.nii.gz)

It's the probability images for labels 0-7.

> I also found another issue is I cannot generate the all the 'probability_images' . It only show five pictures.

All probability images exist (see below).  However, the problem with what you're trying to do is the probability image ``parc_tct['probability_images'][5]`` is essentially all zeros.  ``ants.plot(...)`` doesn't plot it because, internally it's trying to create a mask from the image to render only the salient region and that doesn't work with am image of all zeros.   But that's an issue with ``ants.plot(...)`` and not the antspynet function.  The reason why it creates all zeros is because the label 5 region is relatively tiny in the space of the DevCCF template and it's not found in the lower resolution sample image.

```
>>> ants.plot(parc_tct['probability_images'][0])
>>> ants.plot(parc_tct['probability_images'][1])
>>> ants.plot(parc_tct['probability_images'][2])
>>> ants.plot(parc_tct['probability_images'][3])
>>> ants.plot(parc_tct['probability_images'][4])
>>> ants.plot(parc_tct['probability_images'][5])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ntustison/anaconda3/lib/python3.11/site-packages/ants/plotting/plot.py", line 389, in plot
    min_idx = nonzero[0] + slice_buffer[0]
              ~~~~~~~^^^
IndexError: index 0 is out of bounds for axis 0 with size 0
>>> ants.plot(parc_tct['probability_images'][6])
>>> ants.plot(parc_tct['probability_images'][7])
>>> parc_tct['probability_images'][5].shape
(128, 117, 96)
>>> parc_tct['probability_images'][5].max()
3.7560965e-06
>>> parc_tct['probability_images'][5].min()
0.0
```

**Comment by TsungChihTsai** [comment]
Thanks for your guidance! 

I confirm that the label of brain area:  "- 2: Prelimbic area", "- 3: Infralimbic area", "- 4: Medial group of the dorsal thalamus", "- 5: Reticular nucleus of the thalamus", "- 6: Hippocampal formation" and "- 7: Cerebellum". 

It matches your labels. 
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/853d24ea-9ae6-444c-ba19-7077b54134a6)

I can find most of my desired brain area. 
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/82954bd4-e530-4cd0-9bf5-6614edfc46d3)
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/6a46c683-5948-4a0a-ac5f-f2917bcdd8bb)
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/2ab43e31-734c-4989-8a74-7d256058879b)
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/ab5690c9-7578-45be-aea6-4798409d1082)
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/c476255a-7162-41c9-b63b-c801b3a88dbb)

So, this result shows that "antspynet.mouse_brain_parcellation(mouse_t2_n4, mask=None, which_parcellation="tct", return_isotropic_output=True,  verbose=True)" **cannot recognize** "**Reticular nucleus of the thalamus**"  ["- 5: Reticular nucleus of the thalamus", (parc_tct['probability_images'][5])]. **Because this brain area is too small to detect?**

**Comment by ntustison** [comment]
> Because this brain area is too small to detect?

Take a look at the input image.  Are you able to discern that particular structure?  I can't.  That should tell you something about expectations for this image.

**Comment by TsungChihTsai** [comment]
Thanks for remind me to check it. 

Yes, you are right! The input images in horizontal section are not clear. 
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/66b2d23e-dea1-4d92-aed1-7f7ca6f90b4f)

I'm not sure why, but when I change the axis from horizontal to coronal using the same images (https://figshare.com/ndownloader/files/45289309), the details become clearer than in the original input.  

When I use the "coronal" section, it looks better. And, it exhibits "reticular nucleus of the thalamus" after using which_parcellation="tct". 

input image (coronal section)
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/4641565a-1d79-4a88-b47b-9fce2eddfe82)


mouse_brain_parcellation by the mode of "which_parcellation="tct""
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/b26e658e-9c74-4f53-be01-91d356d894bc)


Thus, if our input displays more recognizable features, we can achieve greater accuracy in identifying brain areas by mouse_brain_parcellation. Is it corrected?

**Comment by ntustison** [comment]
> Thus, if our input displays more recognizable features, we can achieve greater accuracy in identifying brain areas by mouse_brain_parcellation. Is it corrected?

Yes.  Your results are going to be correlated with the quality of the input image.

**Comment by TsungChihTsai** [comment]
I asked our core facility for mouse MRI sample images, which they provided. When I tried to analyze it, I found that using the whole picture affect detection due to the surrounding tissue.

<img src="https://github.com/ANTsX/ANTsPyNet/assets/123632629/6be7094c-8123-4952-bfb8-ec01ff297dc8" width="300" height="400" alt="1">
<img src="https://github.com/ANTsX/ANTsPyNet/assets/123632629/4a94389c-c49b-43a0-b7f4-6b84d70f0ddf" width="300" height="400" alt="1">
<img src="https://github.com/ANTsX/ANTsPyNet/assets/123632629/e1594108-a704-477b-b602-f81c99497aae" width="300" height="400" alt="1">
<img src="https://github.com/ANTsX/ANTsPyNet/assets/123632629/104fe0dd-54d4-405d-ac99-6fcdb0d92a2f" width="300" height="400" alt="1">
<img src="https://github.com/ANTsX/ANTsPyNet/assets/123632629/cbc08fba-3bd1-436c-a451-789213abdb59" width="300" height="400" alt="1">
<img src="https://github.com/ANTsX/ANTsPyNet/assets/123632629/c638650a-5ce6-402d-ad22-1b36302ad7ac" width="300" height="400" alt="1">
<img src="https://github.com/ANTsX/ANTsPyNet/assets/123632629/ff5f1c20-84ac-4fdf-befc-22a38b8f0ff8" width="300" height="400" alt="1">

I also use different way to present the images: 
<img src="https://github.com/ANTsX/ANTsPyNet/assets/123632629/9d9463bc-650f-41e3-8e37-b1d922f3b939" width="300" height="300" alt="1">
and then analyze again: 
<img src="https://github.com/ANTsX/ANTsPyNet/assets/123632629/2c6e4f58-adfc-4a0c-9cca-23e9b4936e16" width="400" height="300" alt="1">

If I try to specifically crop the whole brain, using "antspynet.mouse_brain_parcellation" results in an error. I noticed that just rotating or cropping the images causes the same error. 
<img src="https://github.com/ANTsX/ANTsPyNet/assets/123632629/cee4d803-5693-4be0-a059-ccdd62eabc06" width="300" height="300" alt="1">
![image](https://github.com/ANTsX/ANTsPyNet/assets/123632629/6087c78e-c2e2-45ee-a062-b392e7da190f)

Could you please guide me how can I just use the whole brain area without including other tissues? Or, should I increase the image resolution first?

**Comment by ntustison** [comment]
Always use ITK-SNAP to visualize the images to ensure consistency with ANTsX tools.
