### ISSUE TITLE
Question about antsxnet_cache_directory (string) in antspynet.utilities.brain_extraction.

### ISSUE THREAD

**Issue by Lucifer201210** [ANTsX/ANTsPyNet#128]
Hi, When I exacted brain using `antspynet.utilities.brain_extraction` according to AntsPyNet document (https://antsx.github.io/ANTsPyNet/docs/build/html/utilities.html#applications), an error happened. 

![截图 2024-08-22 00-41-48](https://github.com/user-attachments/assets/b3117706-5336-41d2-a30a-f2844837ad3e)

According this document, the `antsxnet_cache_directory `was used to store the downloaded template and model weights. I haved download `brainExtractionRobustT1.h5` and `S_template3_resampled.nii.gz` in a folder. Then  I set `antsxnet_cache_directory ` to this folder path. the code was as following:

![截图 2024-08-22 00-50-33](https://github.com/user-attachments/assets/832b1cb4-d0b1-4238-b6a2-e44b49a6d9de)

![截图 2024-08-22 00-50-59](https://github.com/user-attachments/assets/e717ad01-5f00-484f-9793-e632295836d3)

 `brainExtractionRobustT1.h5` and `S_template3_resampled.nii.gz`  were in `/home/wei/DeepLearning/Model_pth/`, Since I haved   downloaded template and model weights to the folder path which `antsxnet_cache_directory` was pointed to，why `antspynet.utilities.brain_extraction` still need to download data from https://ndownloader.figshare.com/files/22597175

Then I copy `brainExtractionRobustT1.h5` and `S_template3_resampled.nii.gz` to `~/.keras/ANTsXNet`,  and run `antspynet.utilities.brain_extraction` twice, the same error happed.

![截图 2024-08-22 01-04-35](https://github.com/user-attachments/assets/e2d08050-7303-4366-b6b1-28519a0cf90f)

When I copy https://ndownloader.figshare.com/files/22597175 to my google chrome, It automatically download `S_template3_resampled.nii.gz` . I don't know the reason why error happend.

**Comment by cookpa** [comment]
Code looks correct, always good to verify that the file is accessible before calling brain_extraction

```
import os
mycachedir = '/home/wei/DeepLearning/Model_pth/'
os.listdir(mycachedir)
os.access(os.path.join(mycachedir, 'brainExtractionRobustT1.h5'), os.R_OK)
```

**Comment by ntustison** [comment]
And, fyi, I would always check with the self-contained, minimal tutorials for antsxnet available [here](https://gist.github.com/ntustison/12a656a5fc2f6f9c4494c88dc09c5621).

**Comment by Lucifer201210** [comment]
> Code looks correct, always good to verify that the file is accessible before calling brain_extraction
> 
> ```
> import os
> mycachedir = '/home/wei/DeepLearning/Model_pth/'
> os.listdir(mycachedir)
> os.access(os.path.join(mycachedir, 'brainExtractionRobustT1.h5'), os.R_OK)
> ```

Thanks! I tried the code above and the file is accessible.

![截图 2024-08-23 14-52-02](https://github.com/user-attachments/assets/61ce4b9a-2885-410c-bb66-f9a6e6a536e4)

The same error happened as before. Is it needed to install any other dependencies or `Tensorflow`/`pytorch` before using `brain_exaction`?

**Comment by Lucifer201210** [comment]
> And, fyi, I would always check with the self-contained, minimal tutorials for antsxnet available [here](https://gist.github.com/ntustison/12a656a5fc2f6f9c4494c88dc09c5621).

Thanks! I read the minimal tutorials and still don't know the reason why error happened. Then I newly create another conda environment to install `ANTsPy` according to the tutorials. The installation code is as follows:

`git clone https://github.com/ANTsX/ANTsPyNet

cd ANTsPyNet

python3 setup.py install
`

It is failed to install `ANTsPy` through this way.  I successfully installed `ANTsPy` before using `pip install antspyx`. Is there any difference between ` python3 setup.py install` and `pip install antspyx`. Which one is better?

![截图 2024-08-23 15-08-43](https://github.com/user-attachments/assets/6539259c-5a5f-4168-b4ff-7f7f17af56ef)

**Comment by cookpa** [comment]
I made #130 in an effort to simplify cache issues like this
