### ISSUE TITLE
Getting an error when trying the super resolution tutorial

### ISSUE THREAD

**Issue by GuillaumeTh** [ANTsX/ANTsPyNet#134]
Hi, 

I am trying to run the super resolution tutorial but I got the following error when I am running this: `t1_sr = antspynet.mri_super_resolution(t1_lr, verbose=True)`

Error:

```
TypeError: Error when deserializing class 'Conv3DTranspose' using config={'name': 'conv3d_transpose_4', 'trainable': True, 'dtype': 'float32', 'filters': 64, 'kernel_size': [6, 6, 6], 'strides': [2, 2, 2], 'padding': 'same', 'data_format': 'channels_last', 'groups': 1, 'activation': 'linear', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None, 'output_padding': None}.

Exception encountered: Unrecognized keyword arguments passed to Conv3DTranspose: {'groups': 1}
```

Do you have an idea how to correct this ?

**Comment by ntustison** [comment]
Looks like some [keras version incompatibilities](https://github.com/keras-team/keras/issues/19441).  

This is actually work from @stnava with his repository [here](https://github.com/stnava/siq).  Perhaps it would be best to remove this functionality from the set of ANTsXNet applications.  @stnava, what do you think?  Would it be best to simply point everybody to your ``siq`` repo for super resolution?

**Comment by stnava** [comment]
yes - I think that might be reasonable .... the only issue as yet is that the (large collection of) models is not easy to find.   I can put them on figshare though.    some are [already available](https://figshare.com/articles/software/siqmodels/21718412) ...

**Comment by ntustison** [comment]
Okay, so just to confirm---I should go ahead and remove super resolution from antsxnet, correct?

**Comment by stnava** [comment]
maybe leave it there but make it return a message about where to look?

**Comment by ntustison** [comment]
Sounds good.  I'll do that.

**Comment by ntustison** [comment]
@GuillaumeTh --- closing this issue.  Please follow-up with @stnava over at the [siq repo](https://github.com/stnava/siq).
