### ISSUE TITLE
Any example of training model with my own dataset?

### ISSUE THREAD

**Issue by kingaza** [ANTsX/ANTsPyNet#140]
Hello guys,

It is a great job.
Now I want to use it with my own dataset, however, I cannot find any snippet about training.

thanks.

Best Regards,
kingaza

**Comment by ntustison** [comment]
Training is not something we formally support.

However,  all the components to perform training are available in the ANTsX repositories.  I also post all the training scripts I use for the distributed models [here](https://github.com/ntustison/ANTsXNetTraining).

**Comment by kingaza** [comment]
Got it. 
thx.
