### ISSUE TITLE
error: Could not find suitable distribution for Requirement.parse('tempfile')

### ISSUE THREAD

**Issue by vsaase** [ANTsX/ANTsPyNet#2]
https://github.com/ANTsX/ANTsPyNet/blob/d3bc7689c853827af825d3be2948417a11f2ac3b/setup.py#L10

when installing i got an error: Could not find suitable distribution for Requirement.parse('tempfile')
I think this is provided by python standard library, so you could remove it here

**Comment by ntustison** [comment]
Thanks.
