### ISSUE TITLE
Batch size parameter in Apply super resolution function 

### ISSUE THREAD

**Issue by ksindwan** [ANTsX/ANTsPyNet#26]
I am running the following code with a 2D CNN model and a 3 channel RGB (96,96,3) image.  Within the apply_super_resolution function, image patches are created, then model prediction and finally generating the super resolution image. 

The model predict statement has a parameter batch_size. But the output from image_patches is (1,96,96,3). I want to understand if the batch_size is being used at all 

```
mdl = tf.keras.models.load_model(model_str)
img = ants.image_read("xray_96.jpg")
ants.set_spacing(gt_img, (0.127, 0.127))
sr_pred = antspynet.apply_super_resolution_model_to_image(img, mdl)
```

**Comment by ntustison** [comment]
Could you point to the section of code to which you're referring and spell it out a bit more?  The code that you provide contains nothing about "output from image_patches."

**Comment by ksindwan** [comment]
Sure, expanding it more. In this [file](https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/super_resolution_utilities.py) the apply_super_resolution_model_to_image function is defined, which is being used by me in the code above. On line 320, model predict statement is called with _batch_size_ as parameter.  The input to the model_predict is image_patches , which for a single 2D images is of shape (1,x,x,3) where x is dimension. My question is, Is the parameter _batch_size_ relevant for 2D image input

**Comment by ntustison** [comment]
Yes.

**Comment by ksindwan** [comment]
Do you mean the sr_model splits the image ?
Also, I have observed that the input to the model.predict is (1,x,x,3). Since it is a single data point, how is it being split ?

**Comment by ntustison** [comment]
Yes, it's not being used here but is probably a remnant from parallel work.
