### ISSUE TITLE
Regarding ANTsPyNet's pre-trained models

### ISSUE THREAD

**Issue by aksh-ai** [ANTsX/ANTsPyNet#39]
Hi,

I highly appreciate the great work by the ANTsX team. I just have a few questions regarding the ANTsPyNet's pre-trained models that are available for Brain Extraction. It'd be really great if you could provide information for the following queries:

1. What are the datasets on which the brain extraction models were trained for T1, T2, and Flair?
2. Can I know about the metrics used and obtained for training, testing, and validation? (Example: Dice Score, IoU score, etc.)
3. Will the library be supporting and providing pre-trained models for PyTorch in the future?

Thank you for your time and help.

**Comment by ntustison** [comment]
https://www.nature.com/articles/s41598-021-87564-6

**Comment by aksh-ai** [comment]
Thanks a lot for the quick response and for clarifying my doubts. Your help is much appreciated.
