### ISSUE TITLE
Brain extraction

### ISSUE THREAD

**Issue by XL258** [ANTsX/ANTsPyNet#42]
Dear ANTsPyNet team,

I tried antspynet.utilities.brain_extraction on T1w images, and the output probability masks look great. 

My next step is to multiply the original image with the probability mask (then threshold with 100) to extract the brain.

However, the image size and sform matrix of the probability mask differed from the original image a bit, so fsl always gave warning when I used fslmaths - mul to multiply images.
”Inconsistent orientations for individual images in pipeline!“

My question is whether this is the correct way to extract the brain (multiply and then set threshold), or there is a way to output the extracted brain directly? Why the image size and sform matrix differed from the original images?

Thanks!

**Comment by ntustison** [comment]
This is probably due to the itk vs. fsl differences in the way the nifti headers are read, which are discussed in various forums.  I'm guessing FSL has some sort of header copying utility which you might want to try.

**Comment by XL258** [comment]
Thank you very much for the help! It solved my problem.
