### ISSUE TITLE
How do I get `antspynet.utilities.cortical_thickness` to work on other contrasts?

### ISSUE THREAD

**Issue by dangom** [ANTsX/ANTsPyNet#48]
For example, on a white-matter nulled T1w MPRAGE.
Does that necessarily require retraining?

Thanks.

**Comment by ntustison** [comment]
You'd have to retrain the segmentation component, i.e. ``deep_atropos``.

**Comment by dangom** [comment]
That makes sense. Thanks for the quick reply.
