### ISSUE TITLE
pre-trained weights

### ISSUE THREAD

**Issue by alon-begin** [ANTsX/ANTsPyNet#5]
hey guys :-)
Thanks for all the models!!
Do you also provide pre-trained weights or at least to the u-net?

**Comment by ntustison** [comment]
Sure, we typically store the weights on figshare and then use [this function](https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/get_pretrained_network.py) to download them for specific applications.  For example, [here's](https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/brain_extraction.py) our brain extraction program which, depending on the modality, downloads the appropriate set of weights.

**Comment by alon-begin** [comment]
got it
Thanks!
