### ISSUE TITLE
DeepFlash for Hippocampal Subfields Segmentation: Reference

### ISSUE THREAD

**Issue by clementpoiret** [ANTsX/ANTsPyNet#52]
Hi,

I am making paper comparing segmentation methods, and as DeepFlash for hippocampal subfields segmentation seems new, I want to include it in my comparison.
The website you reference doesn't really include any specific citable material. Does it have any DOI or preprint paper?

Thanks,
Clément POIRET

**Comment by ntustison** [comment]
Thanks @clementpoiret for your interest.  Unfortunately, the write-up is currently underway and so I don't have a citation for you.

**Comment by clementpoiret** [comment]
Thanks for your answer @ntustison 
So, do you prefer that we do not include Deep Flash in our comparison until you publish a paper?
Also, do you plan to release a version with separate CA2 and CA3 classes?

**Comment by ntustison** [comment]
Hi @clementpoiret, so just a bit of background --- DeepFlash has been a long term collaborative project with Mike Yassa at UCI which evolved from earlier work described in the citations below.  Basically, we had previously used joint label fusion based on Mike's hand-labeled data---kind of a simplified ASHS approach.  This was then implemented in a deep learning framework for improved performance.  The write-up involves not only deep flash results but other ANTsXNet measurements so writing is taking a bit longer.  I talked with Mike, as this is his call, and he would prefer a citation exist before any third-party evaluation.  That way we can actually have an existing description of some of the unique aspects of training and the network.  What is your intended timeline?   As you mention, a possible citation could include a biorxiv/medrxiv preprint.

> Also, do you plan to release a version with separate CA2 and CA3 classes?

No.  I'd have to ask Mike about his specific parcellation choices but I'm guessing he didn't feel comfortable attempting a delineation between CA2/CA3/CA4 on the T1/T2 training data.  

* Brown ES, Kulikova A, Van Enkevort E, Nakamura A, Ivleva EI, Tustison NJ, Roberts J, Yassa MA, Choi C, Frol A, Khan DA, Vazquez M, Holmes T, Malone K (2019a): A randomized trial of an NMDA receptor antagonist for reversing corticosteroid effects on the human hippocampus. Neuropsychopharmacology 44:2263–2267.

* Brown ES, Sayed N, Choi C, Tustison N, Roberts J, Yassa MA, Van Enkevort E, Nakamura A, Ivleva EI, Sunderajan P, Khan DA, Vazquez M, McEwen B, Kulikova A, Frol AB, Holmes T (2019b): A randomized, double-blind, placebo-controlled trial of lamotrigine for prescription corticosteroid effects on the human hippocampus. Eur Neuropsychopharmacol 29:376–383.

* Holbrook AJ, Tustison NJ, Marquez F, Roberts J, Yassa MA, Gillen DL, Alzheimer’s Disease Neuroimaging Initiative (2020): Anterolateral entorhinal cortex thickness as a new biomarker for early detection of alzheimer’s disease. Alzheimers Dement (Amst) 12:e12068.
 
* McMakin DL, Kimbler A, Tustison NJ, Pettit JW, Mattfeld AT (2021): Negative overgeneralization is associated with anxiety and mechanisms of pattern completion in peripubertal youth. Soc Cogn Affect Neurosci.

* Reagh ZM, Noche JA, Tustison NJ, Delisle D, Murray EA, Yassa MA (2018): Functional imbalance of anterolateral entorhinal cortex and hippocampal dentate/CA3 underlies age-related object pattern separation deficits. Neuron 97:1187–1198.e4.

* Sinha N, Berg CN, Tustison NJ, Shaw A, Hill D, Yassa MA, Gluck MA (2018): APOE ε4 status in healthy older african americans is associated with deficits in pattern separation and hippocampal hyperactivation. Neurobiol Aging 69:221–229.

**Comment by clementpoiret** [comment]
Thanks a lot for all those details.
I completely understand that Mike wants to have a finished paper prior to any third-party test, that's what I thought and why I posted here too.

I don't have a specific timeline, I'm currently manually segmenting new hippocampi to benchmark different tools including ours, so it's taking a lot of time. Maybe I'll compute deepflash's segmentations, but only include them if a paper is published in the meantime.

**Comment by ntustison** [comment]
Sounds good.  I'll post a biorxiv/medrxiv link here after it's posted.

**Comment by ntustison** [comment]
https://www.medrxiv.org/content/10.1101/2023.01.17.23284693v1
