### ISSUE TITLE
Understanding the DKT Parcellation for skull stripped data 

### ISSUE THREAD

**Issue by Jeffotter** [ANTsX/ANTsPyNet#54]
Hi, I am very new to all this and might have somewhat of a novice question. I am attempting to DKT parcellate a brain from a well-known ANDI Dataset in python. I understand that the preprocessing for the Desekan_Killany_Tourville function uses "croppedMni152" to aid in registration during its preprocessing. Is it wrong for me to utilize this preprocessing on an already skull-stripped data set? Or does the Ants account for this? Thank you in advance!

**Comment by ntustison** [comment]
It is preferred if the input is the raw T1 image.  However, you can try to do the [preprocessing](https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/desikan_killiany_tourville_labeling.py#L201-L205) yourself.  Just make sure you set ``do_preprocessing=False``.

**Comment by Jeffotter** [comment]
Thank you Nick, I'll check around to see what I can get, best results so far is using the model as is
