### ISSUE TITLE
Error on tf.keras.models.load_model, missing 'trainable' argument

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTsPyNet#57]
Similar to #50, I get this error whenever trying to load a model:

```
>>> super = antspynet.mri_super_resolution(anat, verbose = True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pcook/tmp/NOT_BACKED_UP/antsPyNetDevel/ANTsPyNet/antspynet/utilities/mri_super_resolution.py", line 45, in mri_super_resolution
    model_sr = tf.keras.models.load_model(model_and_weights_file_name, compile=False)
  File "/opt/miniconda3/envs/antspynetdevel/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/miniconda3/envs/antspynetdevel/lib/python3.8/site-packages/keras/engine/base_layer.py", line 340, in __init__
    raise TypeError(
TypeError: Expected `trainable` argument to be a boolean, but got: None

I got the same error with a different model
```

```
>>> model = tf.keras.models.load_model(antspynet.get_pretrained_network("koniqMS"), compile=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/antspynetdevel/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/miniconda3/envs/antspynetdevel/lib/python3.8/site-packages/keras/engine/base_layer.py", line 340, in __init__
    raise TypeError(
TypeError: Expected `trainable` argument to be a boolean, but got: None
```

The workaround in #50 was to edit the keras `base_layer.py` code, is there another solution? This is with the current master antspynet, on my Mac Catalina. Here's my list of installed packages in this environment

% pip freeze
absl-py==1.0.0
-e git+ssh://git@github.com/ANTsX/ANTsPyNet.git@011d3e22e69ed8e9668b077868f695c115c0138f#egg=antspynet
antspyx==0.3.2
astunparse==1.6.3
cachetools==5.1.0
certifi==2022.5.18.1
charset-normalizer==2.0.12
chart-studio==1.1.0
cloudpickle==2.1.0
cycler==0.11.0
decorator==5.1.1
dm-tree==0.1.7
flatbuffers==1.12
fonttools==4.33.3
gast==0.4.0
google-auth==2.6.6
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.46.3
h5py==3.7.0
idna==3.3
imageio==2.19.2
importlib-metadata==4.11.4
joblib==1.1.0
keras==2.9.0
Keras-Preprocessing==1.1.2
kiwisolver==1.4.2
libclang==14.0.1
Markdown==3.3.7
matplotlib==3.5.2
networkx==2.8.2
nibabel==3.2.2
numpy==1.22.4
oauthlib==3.2.0
opt-einsum==3.3.0
packaging==21.3
pandas==1.4.2
patsy==0.5.2
Pillow==9.1.1
plotly==5.8.0
protobuf==3.19.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.1
PyWavelets==1.3.0
PyYAML==6.0
requests==2.27.1
requests-oauthlib==1.3.1
retrying==1.3.3
rsa==4.8
scikit-image==0.19.2
scikit-learn==1.1.1
scipy==1.8.1
six==1.16.0
statsmodels==0.13.2
tenacity==8.0.1
tensorboard==2.9.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.9.1
tensorflow-estimator==2.9.0
tensorflow-io-gcs-filesystem==0.26.0
tensorflow-probability==0.16.0
termcolor==1.1.0
threadpoolctl==3.1.0
tifffile==2022.5.4
typing_extensions==4.2.0
urllib3==1.26.9
webcolors==1.11.1
Werkzeug==2.1.2
wrapt==1.14.1
zipp==3.8.0

**Comment by ntustison** [comment]
I'm guessing it's the tensorflow version because I still don't have issues running it:

```
$ pip3 freeze
...
tensorboard==2.4.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.5.0rc0
tensorflow-probability==0.12.1
termcolor==1.1.0
...
```

I don't know if we could read in the model with the working, modified keras layer and then write it back out.  I.e., 

```
import antspynet
import tensorflow as tf

model_and_weights_file_name = antspynet.get_pretrained_network("mriSuperResolution")
model_sr = tf.keras.models.load_model(model_and_weights_file_name, compile=False)

# Change "None" to "False"  ¯\_(ツ)_/¯

for i in range(len(model_sr.layers)):
    print(i, model_sr.layers[i].trainable)
    if model_sr.layers[i].trainable is None:
        model_sr.layers[i].trainable = False

# Save the new model

tf.keras.models.save_model(model_sr, "/Users/ntustison/Desktop/mriSuperResolution.h5")
```

Can you try loading the [new model](https://figshare.com/ndownloader/files/35290684) where "trainable == None" has been replaced with "trainable == False"?

**Comment by cookpa** [comment]
OK I hacked my tf.keras. 

When I run the loop above on the old model, I just see True and False, there's not a single None. 

But the new model (from the link above) does work correctly, and generates no errors.

**Comment by ntustison** [comment]
Great.  Glad it worked.  I'll update the url to reflect the new model.

I don't know why you don't see 'None' because that's what the error seems to indicate.  Also, the following is the output when I look at the old vs. new model:

```
>>> for i in range(len(model_sr.layers)):
...     print(i, model_sr.layers[i].trainable)
...     if model_sr.layers[i].trainable is None:
...         model_sr.layers[i].trainable = False
... 
0 True
1 True
2 True
3 True
4 True
5 True
6 True
7 True
8 True
9 True
10 True
11 True
12 None
13 True
14 True
15 True
16 None
17 True
18 True
19 True
20 True
21 None
22 True
23 True
24 None
25 True
26 True
27 True
28 True
29 True
30 True
31 True
32 None
33 True
34 True
35 True
36 None
37 None
38 True
39 True
40 True
41 True
42 True
43 True
44 None
45 True
46 True
47 None
48 None
49 True
50 True
51 True
52 True
53 True
54 True
55 True
56 None
57 True
58 True
59 True
60 None
61 None
62 True
>>> for i in range(len(model_sr.layers)):
...     print(i, model_sr.layers[i].trainable)
... 
0 True
1 True
2 True
3 True
4 True
5 True
6 True
7 True
8 True
9 True
10 True
11 True
12 False
13 True
14 True
15 True
16 False
17 True
18 True
19 True
20 True
21 False
22 True
23 True
24 False
25 True
26 True
27 True
28 True
29 True
30 True
31 True
32 False
33 True
34 True
35 True
36 False
37 False
38 True
39 True
40 True
41 True
42 True
43 True
44 False
45 True
46 True
47 False
48 False
49 True
50 True
51 True
52 True
53 True
54 True
55 True
56 False
57 True
58 True
59 True
60 False
61 False
62 True
```

**Comment by cookpa** [comment]
Oh wait, I don't see None because I set False in my hack. Now I see it

**Comment by ntustison** [comment]
Awesome.  Thanks.

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTsPyNet/commit/cf9f0c0c57607c34842ff0d3b179ee7701ad69a3

**Comment by cookpa** [comment]
Thanks, now I can run the super resolution! 

I looped through the other networks, and saw the same error in these files:

dbpn4x.h5
koniqMS.h5
koniqMS2.h5
koniqMS3.h5
tidsQualityAssessment.h5

**Comment by ntustison** [comment]
Okay, those are all models that @stnava trained.  Presumably we can fix them the same way.  I'll post when I update.

**Comment by cookpa** [comment]
Sounds good, thanks again

**Comment by ntustison** [comment]
Updated accordingly (below).

https://github.com/ANTsX/ANTsPyNet/commit/42a98b81e1efd2767152bf867cd588a02338e1ec

https://github.com/ANTsX/ANTsRNet/commit/ddb678e8ab0c44b49a2d88074a5d060965642ab8



```
import antspynet
import tensorflow as tf

model_filenames = list()
model_filenames.append("dbpn4x")
model_filenames.append("koniqMS")
model_filenames.append("koniqMS2")
model_filenames.append("koniqMS3")
model_filenames.append("tidsQualityAssessment")

output_directory = "/Users/ntustison/Desktop/"

for i in range(len(model_filenames)):
    model = tf.keras.models.load_model(
        antspynet.get_pretrained_network(model_filenames[i]), compile=False)
    print(model_filenames[i])
    print("Old trainable configuration per layer.")
    for j in range(len(model.layers)):
        print(j, model.layers[j].trainable)
        if model.layers[j].trainable is None:
            model.layers[j].trainable = False
    print("New trainable configuration per layer.")
    for j in range(len(model.layers)):
        print(j, model.layers[j].trainable)
    tf.keras.models.save_model(model, output_directory + model_filenames[i] + ".h5")
```
