### ISSUE TITLE
Soft or Hard ground-truth masks?

### ISSUE THREAD

**Issue by charleygros** [ANTsX/ANTsPyNet#6]
Dear ANTsPyNet team,

I was wondering: When training or testing a segmentation model: do you binarize the ground-truth masks, that have been transformed by preprocessing / data augmentation operations, just before feeding the network? Is there a parameter that controls this? If so, what are your thoughts on the best practice?

Cheers

**Comment by ntustison** [comment]
> When training or testing a segmentation model: do you binarize the ground-truth masks, that have been transformed by preprocessing / data augmentation operations, just before feeding the network?

Yes, although that's typically done automatically by choosing a binarizing interpolator.  

> Is there a parameter that controls this?

See above.  You can also use ``ants.threshold_image`` to binarize the result.  

> If so, what are your thoughts on the best practice?

I don't know what you mean.  There doesn't seem to be much of an issue as to whether or not this conforms to "best practice"?

**Comment by charleygros** [comment]
Thanks for your prompt reply @ntustison. Very helpful.

Oh, my question was simply: Do you recommend to threshold my ground-truth masks that have been through the data augmentation operations before feeding them to the network OR not to threshold them (ie it will be a "soft/continuous" mask instead of a binary one)?

**Comment by ntustison** [comment]
I've never evaluated the difference in performance but I would be surprised if it actually mattered, at least in the applications for which we've trained.

**Comment by charleygros** [comment]
Okay, no worries. I was simply not sure which way was the "common way to do it". Thanks for your insights @ntustison :+1:
