### ISSUE TITLE
Pytorch version？

### ISSUE THREAD

**Issue by ElegantLee** [ANTsX/ANTsPyNet#61]
This work is awesome. Will there be a official version of PyTorch?

**Comment by ntustison** [comment]
That’s something we’ve thought about but it isn’t currently a priority.  We don’t necessarily have strong feelings re. PyTorch vs. Keras/Tensorflow.  The main reason why we went with the latter was it’s more evolved state in R at the time.

**Comment by lassoan** [comment]
Thanks for the information. This is awesome!
