### ISSUE TITLE
not an issue just sharing (claustrum)

### ISSUE THREAD

**Issue by samtorrisi** [ANTsX/ANTsPyNet#64]
not an issue just saying i ran the claustrum DL model on some 7T data and it performed well, here's my little tweet:

https://twitter.com/stbmtx/status/1581377429427261441

thanks again for all your hard work!

**Comment by ntustison** [comment]
Nice.  And thanks for posting the paper describing the methodology.  The fact that the authors made the weights available is something we really appreciate.
