### ISSUE TITLE
hypermapper registration assumptions

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTsPyNet#68]
raises an error if t1 is not aligned to flair.   

goes away if registered.  

however, t1 in flair space or other way around?  does it matter?

**Comment by ntustison** [comment]
Thanks for noticing this.  I know that the sysu function requires pre-alignment and I have that in the documentation.  I just forgot that here.  For something like this, I much prefer to put the onus on the user for pre-alignment.

**Comment by stnava** [comment]
thanks - I'd recommend mapping t1 to flair unless there is reason to go the other way.   the reason is that flair can be highly anisotropic.

**Comment by ntustison** [comment]
Yeah, exactly.  Currently working on something else but when archeozoic comes back online, we'll have to discuss where we want to go from here.  Probably should get some input from James.  Anyway, in case you didn't see it, here's the [merge](https://github.com/ANTsX/ANTsPyNet/commit/6bb1b582a3d8a3bf19d905b8ba7efdac3c4f94e1).
