### ISSUE TITLE
allen_brain_leftright_coronal_mask_weights

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTsPyNet#70]
This is set to an empty file, is that intentional? I'm not trying to use it specifically, just trying to update my container for HPC use. I have to cache data because there's no Internet there

https://github.com/ANTsX/ANTsPyNet/blob/0e6a17814d92680d08aa5dff9a70c90679eb25eb/antspynet/utilities/get_pretrained_network.py#L93

**Comment by ntustison** [comment]
There's a couple of "allen" functions that have weights that are not uploaded yet.  It's collaboration work with Jim.  I'll upload them soon.

**Comment by cookpa** [comment]
Got it, thanks.

**Comment by ntustison** [comment]
This should be fixed.
