### ISSUE TITLE
Noisy slices after MRI super resolution

### ISSUE THREAD

**Issue by Zzariry** [ANTsX/ANTsPyNet#72]
Hello,

I am using the super-resolution algorithm with the trained model, and I have noticed that one of every two slices is more noisy than the rest. Do you know how I can fix that, please?
I tested T1w, T2w, and Diffusion images.

Thanks,
Zakaria

**Comment by ntustison** [comment]
Can you post some example images?

**Comment by Zzariry** [comment]
@ntustison Here are 3 successive slices (I zoomed in a little to make the noise more noticeable).

The initial resolution of the data is 0.2 mm.
![Noisy_slices](https://github.com/ANTsX/ANTsPyNet/assets/50558559/52e63c2c-de87-4924-b1a3-ee1db2e875ed)

**Comment by ntustison** [comment]
You'd actually have to post the originals so I can compare.  But, regardless, 0.2 mm resolution is very different from the original training data.  That might be the issue.

**Comment by ntustison** [comment]
Yeah, the original resolution is outside the range of the training data and my guess is that's why it's not doing anything to improve your images.

**Comment by Zzariry** [comment]
Okay thanks for the clarification, can you tell me which resolution is suitable, please?

**Comment by ntustison** [comment]
I'm pretty sure @stnava trained on original resolution data of ~1.0 mm.
