### ISSUE TITLE
Incorrect sform/qform in `croppedMni152`

### ISSUE THREAD

**Issue by dipterix** [ANTsX/ANTsPyNet#77]
Hi ANTs devs,

I was using preprocessing pipeline proposed by your paper for cortical thickness and brain segmentation. I want to obtain the MNI coordinate from the transforms (inside `antspynet.preprocess_brain_image`) Then I realize the sample image `croppedMni152` has incorrect sform/qform (Image IJK voxel space to RAS, in this case MNI152).

```py
>>> import nibabel
>>> import antspynet
>>> img = nibabel.load(antspynet.get_antsxnet_data("croppedMni152"))
>>> img.header.get_sform()
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.]])
>>> img.header.get_qform()
array([[ 1.,  0.,  0., -0.],
       [ 0.,  1.,  0., -0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])
>>> 
```

I wonder if I have an IJK point in `croppedMni152`, How can I obtain the MNI-152 template coordinate?

**Comment by ntustison** [comment]
> has incorrect sform/qform

Are you aware of [ANTs/ITK usage of sform/qform](https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F)?

**Comment by dipterix** [comment]
Hi @ntustison , I do. but the issue is the image `croppedMni152` in your extended data (used for training segmentation) does not have valid sform/qform. That means, the voxel to world affine matrix is invalid in the file. That's why I printed both sform and qform

According to your document: "How NIFTI-1 transforms are read", ANTs reads from sform or qform, or using ANALYZE (backward compatibility). This is consistent with the NIFTI-1 documentation. 

If we look at `antspynet.get_antsxnet_data("croppedMni152")`, the sform_code is 0 (`NIFTI_XFORM_UNKNOWN`), and qform_code is 1 (`NIFTI_XFORM_SCANNER_ANAT`), according to [NIfTI docs](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwikybn-qISAAxXskmoFHWtxARAQFnoECAoQAQ&url=https%3A%2F%2Fnifti.nimh.nih.gov%2Fnifti-1%2Fdocumentation%2Fnifti1fields%2Fnifti1fields_pages%2Fqsform.html&usg=AOvVaw0RU9j8_tpp26ZG1Wi9gYVH&opi=89978449)

Now according to your document, ANTs uses qform:

> How NIFTI-1 transforms are read
> 1. Check the sform matrix to see if it can be decomposed into a rotation matrix with scaling matching the image spacing. If a rotation matrix can be extracted, proceed to step 2. Otherwise use qform.

Since sform is invalid, and qform is a valid full-rank matrix, ANTs uses qform.

`qform` in `antspynet` data `croppedMni152` is 

```
>>> img.header.get_qform()
array([[ 1.,  0.,  0., -0.],
       [ 0.,  1.,  0., -0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])
```

This matrix means the voxel at corner of your volume is the center of the brain (that's not true of course). The MNI152 origin should be somewhere near the center of the volume.

My suggestion is that you can edit your template "croppedMni152" image and fix either qform or sform. It will not affect your antspynet program (deep antropos or DKT-segmentation). However, since the images are trained on `"croppedMni152"`, it would be great if people can also transform their iEEG electrode coordinates to MNI space (it's low-hanging fruit, as long as "croppedMni152" has the correct s/qform)

**Comment by ntustison** [comment]
The image data was never meant to be used by the general user outside the context of the antsxnet pipelines.  I don't mind if they are used but that was never my intent and if other people have assumptions about the data (e.g., the center coordinates of the brain and the relationship to header information), that's on them.  

Having said that, if you want to "fix" the template, post it on figshare, and create a pull request, I would be more than happy to merge it just as long as everything works as it does currently.

**Comment by dipterix** [comment]
Sure, that sounds good. So my question on "croppedMni152" is how did you generate this image?

**Comment by cookpa** [comment]
There's no single MNI coordinate system, there are multiple series of MNI152 templates that are approximately the same but not exactly. 

I would recommend taking the brain image output of the thickness pipeline and registering it to a specific public MNI template for analysis purposes.

**Comment by ntustison** [comment]
Thanks @cookpa .  That was my impression as well.  

> Sure, that sounds good. So my question on "croppedMni152" is how did you generate this image?

I don't have the exact recipe, unfortunately.  In fact, if I were to do it again, I probably wouldn't use MNI152.  I recently posted a cerebellum morphology antsxnet pipeline for which the original data was in "MNI space" and I purposely transformed it out of that space for training and prediction.

**Comment by dipterix** [comment]
> I would recommend taking the brain image output of the thickness pipeline and registering it to a specific public MNI template for analysis purposes.

I'm actually following this path. I realize that when I use ants registration method, the result is pretty weird if I use skull-stripped brain as fixed. Does it sound good to you if I flip the moving and fixing images and use "croppedMni152" as fixed image and skull-stripped brain as moving in this case?

**Comment by dipterix** [comment]
> I recently posted a cerebellum morphology antsxnet pipeline

Can I find that link? Thanks!

**Comment by ntustison** [comment]
I try to keep ANTsXNet organization simple so

**Comment by ntustison** [comment]
Ooops.  Sorry about that.

ANTsXNet location:

https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/cerebellum_morphology.py

Example usage:

https://gist.github.com/ntustison/12a656a5fc2f6f9c4494c88dc09c5621#cerebellum-morphology

**Comment by cookpa** [comment]
> > I would recommend taking the brain image output of the thickness pipeline and registering it to a specific public MNI template for analysis purposes.
> 
> I'm actually following this path. I realize that when I use ants registration method, the result is pretty weird if I use skull-stripped brain as fixed. Does it sound good to you if I flip the moving and fixing images and use "croppedMni152" as fixed image and skull-stripped brain as moving in this case?

I would dispense with croppedMni152 entirely. Here's what I would do:

1. Call ants.cortical_thickness() on the T1w. The outputs should be in the native space of the input T1w
2. Threshold the returned 'segmentation_image' to make a brain mask (threshold it)
3. Run N4 with the T1w and brain mask
4. Run antsRegistration with fixed = [your choice of brain-extracted MNI152 template] and moving = [ masked, bias-corrected T1w).

This should not produce weird results for the MNI152 registration.

Some people use the whole-head images for the MNI152 registration, including skull. This can be beneficial in some cases, eg where the definition of the brain mask is different between the template and moving image. It can also go wrong with some input data, for example with defaced images.

In my opinion, if a good brain mask is available for both images, the non-linear registration works best with the brain extracted.

Either way, either brain extract both images or neither of them, if one is brain-extracted and the other not, the results will always be bad.

**Comment by dipterix** [comment]
Thanks @ntustison , @cookpa this is super helpful! I'm implementing pipelines using ANTsPy and ANTsPyNet to replace some of the FreeSurfer scripts for RAVE and our new electrode localization. 

https://github.com/rave-ieeg/rave-pipelines/blob/main/modules/ants_preprocessing/main.Rmd

Also ANTsPy and ANTsPyNet are available in R via https://cran.r-project.org/package=rpyANTs

**Comment by cookpa** [comment]
Sounds good. As @ntustison says, if you don't need thickness, you can do the processing much faster by directly calling `brain_extraction`. If you want segmentation but not thickness, use `deep_atropos`.

**Comment by ntustison** [comment]
> Also ANTsPy and ANTsPyNet are available in R via https://cran.r-project.org/package=rpyANTs

This is great but are you aware of our ANTsR and ANTsRNet projects?

**Comment by dipterix** [comment]
> This is great but are you aware of our ANTsR and ANTsRNet projects?

Yes, those are great packages. Our core packages are on CRAN, which has stringent policy that prevents us from using ANTsR. Besides we also want to make users install and start to use RAVE within 5-10 min. Also don't worry, `rpyANTs` has a python interpreter that allows ANTsPyx to share memories with R. It's not using external shell calls.

**Comment by ntustison** [comment]
Great.  Just wanted to make sure you weren't doing any extra work.
