### ISSUE TITLE
Image orientation is changed.

### ISSUE THREAD

**Issue by GYDDHPY** [ANTsX/ANTsPyNet#81]
Hi, can you share some details of model training preprocess or final image saving procedure? I found that the image orientation is changed, seems like is rotated 180 degree. The image orientation is important to my application.

Looking forward to your reply.

**Comment by ntustison** [comment]
Please be more specific in what you're trying to do.  Command calls and some data specifics would be most helpful.

**Comment by GYDDHPY** [comment]
Thank you for your rapid reply. I was try to do super resolution. I have found the wrong usage of the command. Sorry to bother.
Best wishes.
