### ISSUE TITLE
DKT label 14 missing in help

### ISSUE THREAD

**Issue by samtorrisi** [ANTsX/ANTsPyNet#82]
this is like the tiniest detail issue, but I'm finding the desikan_killiany_tourville_labeling() function super useful for generating noise ROIs for resting state fMRI data cleaning. might you add the label 14 (3rd ventricle) to your "inner label" help description? it's successfully being segmented and yet it's not in the help doc. thanks!

**Comment by ntustison** [comment]
Thanks.  I hadn't noticed that.  It's updated in both ANTsRNet and ANTsPyNet.

**Comment by samtorrisi** [comment]
awesome
