### ISSUE TITLE
Hi，I encounter one problem about using antspynet.utilities.deep_atropos !

### ISSUE THREAD

**Issue by FreshmanMa** [ANTsX/ANTsPyNet#84]
Hi,
I use the code below to segement the processed HCP1200 MRI.nii.gz data with CPU? But the result is not right， can you give me some advice?  Should I use GPU?  Or the Parameters of deep_atropos is not right?  How to set the parameter ,use_spatial_priors ?

`file_path = './dataset/test_GT_264/996782.nii.gz' `
`image = ants.image_read(file_path)`
`segmentation_dict = antspynet.utilities.deep_atropos(image, do_preprocessing=True)`
`segmentation_image = segmentation_dict['segmentation_image']`
`segmentation_probability = segmentation_dict['probability_images']`
`ants.image_write(segmentation_image, "./GT_segmentation_996782.nii.gz")`

<img width="847" alt="自己的分割结果" src="https://github.com/ANTsX/ANTsPyNet/assets/93995539/54baedd9-b382-4bc9-813f-27ca6eda00ff">

**Comment by ntustison** [comment]
Try using an input image that isn't skull-stripped.

**Comment by FreshmanMa** [comment]
> Try using an input image that isn't skull-stripped.

Sorry, it doesn't work! I wanna know when  I use the code `image = ants.image_read(673455.nii.gz)`  `segmentation_dict = antspynet.utilities.deep_atropos(image, do_preprocessing=True, verbose=True)` and get the results, how should save the segmentation as nii.gz or other format?   I provide one example of my experiment results,  would you mind help me to have a try? Can you provide the detail code about save the segmentation results of deep_atropos? Thanks a lot!
[531536.nii.gz](https://github.com/ANTsX/ANTsPyNet/files/12268529/531536.nii.gz) (the data is skull-stripped)

**Comment by FreshmanMa** [comment]
> Hi, I use the code below to segement the processed HCP1200 MRI.nii.gz data with CPU? But the result is not right， can you give me some advice? Should I use GPU? Or the Parameters of deep_atropos is not right? How to set the parameter ,use_spatial_priors ?
> 
> `file_path = './dataset/test_GT_264/996782.nii.gz' ` `image = ants.image_read(file_path)` `segmentation_dict = antspynet.utilities.deep_atropos(image, do_preprocessing=True)` `segmentation_image = segmentation_dict['segmentation_image']` `segmentation_probability = segmentation_dict['probability_images']` `ants.image_write(segmentation_image, "./GT_segmentation_996782.nii.gz")`
> 
> <img alt="自己的分割结果" width="847" src="https://user-images.githubusercontent.com/93995539/256178325-54baedd9-b382-4bc9-813f-27ca6eda00ff.png">

I think my code is wrong!

**Comment by FreshmanMa** [comment]
> Try using an input image that isn't skull-stripped.
I use the following code to have a try. There is another question！ I think it's my code is wrong for save the the segmentation results of deep_atropos?

`file_path = './dataset/test_GT_264/673455.nii.gz'`
`segmentation_dict = antspynet.utilities.deep_atropos(image, do_preprocessing=False, verbose=True)`
`segmentation_image = segmentation_dict['segmentation_image']`
`ants.image_write(segmentation_image, "./GT_segmentation_673455.nii.gz")`

the results is like the following img.
![分割结果不用 d0_processed=False](https://github.com/ANTsX/ANTsPyNet/assets/93995539/047e3f95-b179-4972-b7ac-520a18beefc7)

and the run the code, print information .
![image](https://github.com/ANTsX/ANTsPyNet/assets/93995539/8e4e2bc5-aad6-45b3-b682-aa89fd8a8e02)

**Comment by ntustison** [comment]
Again, please use a whole head image.  Using the do_preprocessing=False option is only for advanced users.

**Comment by FreshmanMa** [comment]
> Again, please use a whole head image. Using the do_preprocessing=False option is only for advanced users.
Ok, I do that, and get the result which seems right, Like the following first picture.  But my data is skull-stripped, so I use `do_preprocessing=False `, so what should I do？I feel confused because someone else do the same work on the data which is skull-stripped, and they get the correct results. Like the following second picture. So, I need your help, thanks for your reply!
![results_with_skull-stripped](https://github.com/ANTsX/ANTsPyNet/assets/93995539/8a143653-a72a-41a5-8c11-2ccb141b1460)

![image](https://github.com/ANTsX/ANTsPyNet/assets/93995539/68df09b6-2ed2-4c04-8c26-096e3ab1e15a)

Thanks again!

**Comment by FreshmanMa** [comment]
> > Again, please use a whole head image. Using the do_preprocessing=False option is only for advanced users.
> > Ok, I do that, and get the result which seems right, Like the following first picture.  But my data is skull-stripped, so I use `do_preprocessing=False `, so what should I do？I feel confused because someone else do the same work on the data which is skull-stripped, and they get the correct results. Like the following second picture. So, I need your help, thanks for your reply!
> > ![results_with_skull-stripped](https://user-images.githubusercontent.com/93995539/258619507-8a143653-a72a-41a5-8c11-2ccb141b1460.png)
> 
> ![image](https://user-images.githubusercontent.com/93995539/258620056-68df09b6-2ed2-4c04-8c26-096e3ab1e15a.png)
> 
> Thanks again!

I see  deep_atropos.py , t1 can be one processed data.
![image](https://github.com/ANTsX/ANTsPyNet/assets/93995539/2af4ad0f-4ea1-4e42-b390-44a8b6ebe37a)

**Comment by ntustison** [comment]
> I see deep_atropos.py , t1 can be one processed data.

I wrote deep_atropos.py (including the help text above) so I understand how it should and can be run.  Some preprocessing steps are more conducive to ``deep_atropos`` producing correct results than others (eg, denoising and bias correction).  Other preprocessing steps, such as skull-stripping, is not.  

The reason why ``deep_atropos`` is not meant to be run with skull-stripped data *for the general user* is that different packages have different flavors of skull-stripping.  Just compare the results from ``antspynet.brain_extraction(t1, modality="t1nobrainer")``, which is a FreeSurfer-trained network, vs. ``antspynet.brain_extraction(t1, modality="t1")`` which is ANTs-style.  ``deep_atropos`` was trained on ANTs-style skull-stripped data and it would be incorrect to run it any other way.  If you're an advanced user, and you understand those implications, then you should be able to easily peruse the source code and determine the steps that would allow you to run deep_atropos on your pre-skull-stripped data.  But I'm not going to explicitly lay out those steps in any help requests because I don't want users to run ``deep_atropos`` incorrectly.

**Comment by FreshmanMa** [comment]
> > I see deep_atropos.py , t1 can be one processed data.
> 
> I wrote deep_atropos.py (including the help text above) so I understand how it should and can be run. Some preprocessing steps are more conducive to `deep_atropos` producing correct results than others (eg, denoising and bias correction). Other preprocessing steps, such as skull-stripping, is not.
> 
> The reason why `deep_atropos` is not meant to be run with skull-stripped data _for the general user_ is that different packages have different flavors of skull-stripping. Just compare the results from `antspynet.brain_extraction(t1, modality="t1nobrainer")`, which is a FreeSurfer-trained network, vs. `antspynet.brain_extraction(t1, modality="t1")` which is ANTs-style. `deep_atropos` was trained on ANTs-style skull-stripped data and it would be incorrect to run it any other way. If you're an advanced user, and you understand those implications, then you should be able to easily peruse the source code and determine the steps that would allow you to run deep_atropos on your pre-skull-stripped data. But I'm not going to explicitly lay out those steps in any help requests because I don't want users to run `deep_atropos` incorrectly.

Thanks, I will do my best to run deep_atropos on your pre-skull-stripped data. Thanks again!

**Comment by FreshmanMa** [comment]
> > I see deep_atropos.py , t1 can be one processed data.
> 
> I wrote deep_atropos.py (including the help text above) so I understand how it should and can be run. Some preprocessing steps are more conducive to `deep_atropos` producing correct results than others (eg, denoising and bias correction). Other preprocessing steps, such as skull-stripping, is not.
> 
> The reason why `deep_atropos` is not meant to be run with skull-stripped data _for the general user_ is that different packages have different flavors of skull-stripping. Just compare the results from `antspynet.brain_extraction(t1, modality="t1nobrainer")`, which is a FreeSurfer-trained network, vs. `antspynet.brain_extraction(t1, modality="t1")` which is ANTs-style. `deep_atropos` was trained on ANTs-style skull-stripped data and it would be incorrect to run it any other way. If you're an advanced user, and you understand those implications, then you should be able to easily peruse the source code and determine the steps that would allow you to run deep_atropos on your pre-skull-stripped data. But I'm not going to explicitly lay out those steps in any help requests because I don't want users to run `deep_atropos` incorrectly.

Thanks again！ Inspired by you, I get the results I want!  Thanks a lot!
![image](https://github.com/ANTsX/ANTsPyNet/assets/93995539/de1ee5b7-7912-4e5b-b3de-3779a7fac4f9)
