### ISSUE TITLE
consider using pins to store pretrained networks

### ISSUE THREAD

**Issue by ncullen93** [ANTsX/ANTsPyNet#94]
Using the [pins package](https://rstudio.github.io/pins-python/) to store pretrained networks could be a great improvement over hard-coding urls on figshare. It makes it very easy to upload network weights to AWS S3 or other sources directly from Python. It automatically versions data if you overwrite it and supports metadata. It caches downloaded data. It will be easier to search for available networks. Other people could potentially share their own pretrained networks. And another added benefit is that it works in both R and Python. 

It's basically as simple as this:

```python
board = pins.board_s3('mybucket')
board.pin_write(my_network_weights, 'network_name')
```

Then you use `pin_list` to list all pins (pretrained networks) on a board and `pin_read` to download them. So the big manually curated dictionary of pretained networks could be replaced by one call to `pin_read(pretrained_network_name)`

**Comment by ntustison** [comment]
This seems like a really good idea.  We're not really tied to Figshare other than it was the most convenient thing we found at the time.   I don't know when I'd be able to get to this but it wouldn't be for at least a couple months.

**Comment by ncullen93** [comment]
Ok, I really appreciate your honest assessment. I am going to try to implement this - along with the other ideas for data augmentation / sampling, high-level training, explainability, and launching cloud jobs - in a different, personal repo and hang low on ANTsPyNet until you have more time to discuss and review changes. Then maybe we can see if there's anything worth merging!
