### ISSUE TITLE
Seeking GPU Recommendations for Optimizing ANTsXNet Performance

### ISSUE THREAD

**Issue by GayanSamuditha** [ANTsX/ANTsPyNet#96]
@ntustison  @cookpa 

My team and I are currently utilizing the ANTsXNet library for cortical thickness calculations, specifically drawing upon the repository available at [](https://github.com/ntustison/PaperANTsX.) Our work involves processing images from the ADNI 1, 3Y 3T dataset, encompassing 352 subjects.

During our operations, we've encountered a challenge with the processing speed; we're only able to process about 18 images over a span of 24 hours. This rate significantly limits our research efficiency and scale of analysis.

Given the critical nature of this work, we're actively looking for ways to optimize our processing capabilities. In that context, we would greatly appreciate any recommendations you might have regarding GPU hardware. Specifically, we're interested in learning:

GPU Compatibility and Recommendations:
Are there specific GPU models (e.g., NVIDIA V100, A100) that you have found to significantly enhance the performance of the ANTsXNet libraries?
Could you share any insights or experiences regarding the optimal hardware setup that ensures the best support for running ANTsX?

**Comment by cookpa** [comment]
The majority of the time will be taken by the thickness estimation itself, which is part of ANTsPy. The input to the thickness estimation is the output of deep_atropos, which is much faster even without a GPU. 

Unfortunately, the thickness calculation does not have a GPU implementation, but it can run with multiple CPU threads.

**Comment by ntustison** [comment]
The number of threads will affect the cortical thickness processing which, depending on your computational capabilities, you might want to increase.
